const ACTION_TYPES = {
  SIGN_UP_START_TO_SIGN_UP: Symbol("SIGN_UP_START_TO_SIGN_UP"),
  SIGN_UP_SUCCEEDED_TO_SIGN_UP: Symbol("SIGN_UP_SUCCEEDED_TO_SIGN_UP"),
  SIGN_UP_FAILED_TO_SIGN_UP: Symbol("SIGN_UP_FAILED_TO_SIGN_UP"),
};
